namespace KrishiLink.Models.ViewModels
{
    /// <summary>
    /// Represents a tier in the fixed points-to-discount conversion table.
    /// </summary>
    public class FixedConversionTierViewModel
    {
        public int PointsRequired { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal DiscountTaka => DiscountAmount;
        public decimal Multiplier { get; set; }
        public decimal EffectiveMultiplier => Multiplier;
        public string BonusText { get; set; } = string.Empty;
        public string PromoCodePrefix { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public bool IsBestValue { get; set; }
    }

    /// <summary>
    /// Information about the farmer's current loyalty tier status and progression.
    /// </summary>
    public class LoyaltyTierInfo
    {
        public string TierName { get; set; } = "Bronze Farmer";
        public string TierBadgeClass { get; set; } = "bg-secondary";
        public string BadgeColorClass => TierBadgeClass;
        public string TierColor { get; set; } = "#cd7f32";
        public string TierIcon { get; set; } = "🥉";
        public decimal DiscountMultiplier { get; set; } = 1.0m;
        public int MinPoints { get; set; }
        public int MaxPoints { get; set; }
        public string NextTierName { get; set; } = "Silver Farmer";
        public int PointsToNextTier { get; set; }
        public int ProgressPercentage { get; set; }
        public List<string> Perks { get; set; } = new();
    }

    /// <summary>
    /// Item in the farmer's point transaction ledger.
    /// </summary>
    public class PointTransactionItemViewModel
    {
        public int Id { get; set; }
        public int Points { get; set; }
        public bool IsCredit => Points > 0;
        public string Type { get; set; } = string.Empty;
        public string BadgeColorClass => Type switch
        {
            "Earned" => "bg-success text-white",
            "Redeemed" => "bg-primary text-white",
            "Bonus" => "bg-warning text-dark",
            "Refunded" => "bg-info text-dark",
            "VoucherGenerated" => "bg-secondary text-white",
            _ => "bg-light text-dark"
        };
        public string Description { get; set; } = string.Empty;
        public string? BookingType { get; set; }
        public int? BookingId { get; set; }
        public string? BookingCode { get; set; }
        public string? PromoCode { get; set; }
        public decimal? DiscountAmount { get; set; }
        public decimal? AmountSpent { get; set; }
        public DateTime CreatedAt { get; set; }
        public string RelativeTime { get; set; } = string.Empty;
    }

    /// <summary>
    /// Active promo voucher generated by the farmer.
    /// </summary>
    public class LoyaltyVoucherViewModel
    {
        public string Code { get; set; } = string.Empty;
        public string PromoCode => Code;
        public decimal DiscountAmount { get; set; }
        public int PointsCost { get; set; }
        public DateTime GeneratedAt { get; set; }
        public DateTime CreatedAt => GeneratedAt;
        public bool IsRedeemed { get; set; }
    }

    /// <summary>
    /// Full view model for the Farmer Loyalty Hub page (/Loyalty).
    /// </summary>
    public class LoyaltyHubViewModel
    {
        public string FarmerId { get; set; } = string.Empty;
        public string FarmerName { get; set; } = string.Empty;
        public int CurrentPoints { get; set; }
        public decimal EstimatedDiscountValue { get; set; }
        public int LifetimeEarnedPoints { get; set; }
        public int LifetimeEarned => LifetimeEarnedPoints;
        public int LifetimeRedeemedPoints { get; set; }
        public decimal TotalSavingsTaka => EstimatedDiscountValue;
        public int CompletedBookingsCount { get; set; }

        public LoyaltyTierInfo Tier { get; set; } = new();
        public LoyaltyTierInfo CurrentTier => Tier;
        public string NextTierName => Tier?.NextTierName ?? string.Empty;
        public int PointsToNextTier => Tier?.PointsToNextTier ?? 0;
        public int ProgressToNextTierPercent => Tier?.ProgressPercentage ?? 0;

        public List<FixedConversionTierViewModel> ConversionTiers { get; set; } = new();
        public List<LoyaltyVoucherViewModel> ActiveVouchers { get; set; } = new();
        public List<PointTransactionItemViewModel> Transactions { get; set; } = new();
        public List<PointTransactionItemViewModel> RecentTransactions => Transactions;
    }

    /// <summary>
    /// Result returned when validating a promo code or applying loyalty points.
    /// </summary>
    public class LoyaltyDiscountResult
    {
        public bool IsValid { get; set; }
        public decimal DiscountAmount { get; set; }
        public int PointsRequired { get; set; }
        public string PromoCode { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public decimal OriginalTotal { get; set; }
        public decimal DiscountedTotal { get; set; }
        public int PointsToEarn { get; set; }
        public int RemainingPoints { get; set; }
    }

    /// <summary>
    /// Request model sent when validating or applying a promo code / point redemption via AJAX.
    /// </summary>
    public class ApplyPromoRequestViewModel
    {
        public string? PromoCode { get; set; }
        public int? PointsToRedeem { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal GrossAmount { get => TotalAmount; set => TotalAmount = value; }
        public string BookingType { get; set; } = "Equipment";
        public int ItemId { get; set; }
    }

    /// <summary>
    /// Mini widget rendered on the farmer dashboard.
    /// </summary>
    public class FarmerDashboardLoyaltyWidgetViewModel
    {
        public int CurrentPoints { get; set; }
        public decimal EstimatedDiscountValue { get; set; }
        public string TierName { get; set; } = "Bronze Farmer";
        public string TierBadgeClass { get; set; } = "bg-secondary";
        public string TierIcon { get; set; } = "🥉";
        public string TierIconClass { get => TierIcon; set => TierIcon = value; }
        public decimal DiscountMultiplier { get; set; } = 1.0m;
        public int ActiveVouchersCount { get; set; }
        public string NextTierName { get; set; } = "Silver Farmer";
        public int PointsToNextTier { get; set; }
        public int ProgressPercentage { get; set; }
        public int ProgressToNextTierPercent { get => ProgressPercentage; set => ProgressPercentage = value; }
    }
}
