using System;
using System.Collections.Generic;
using KrishiLink.Models.Entities;

namespace KrishiLink.Models.ViewModels
{
    /// <summary>
    /// Actionable nudge item generated by matching weather telemetry with crop calendar stages.
    /// </summary>
    public class WeatherSuggestionItem
    {
        public string Id { get; set; } = string.Empty;
        public string NudgeType { get; set; } = string.Empty; // StorageProtection, FastHarvesting, TillageIrrigation, DiseasePrevention
        public string Title { get; set; } = string.Empty;
        public string BanglaTitle { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public string BanglaMessage { get; set; } = string.Empty;
        public string ActionUrl { get; set; } = string.Empty;
        public string ActionText { get; set; } = string.Empty;
        public string BanglaActionText { get; set; } = string.Empty;
        public string ActionIcon { get; set; } = "bi-arrow-right";
        public string BadgeClass { get; set; } = "warning";
        public string BadgeText { get; set; } = "Advisory";
        public string BanglaBadgeText { get; set; } = "পরামর্শ";
        public string IconClass { get; set; } = "bi-lightbulb-fill";
        public bool IsCritical { get; set; } = false;
        public int Priority { get; set; } = 1;
    }

    /// <summary>
    /// Composite proactive suggestion model rendered on Farmer Dashboard and Advisory views.
    /// </summary>
    public class WeatherSuggestionViewModel
    {
        public string District { get; set; } = "Bogra";
        public string Division { get; set; } = "Rajshahi";
        public string FarmerCrop { get; set; } = "Rice (Boro)";
        public string BanglaCrop { get; set; } = "বোরো ধান";
        public string CropStage { get; set; } = "Growing"; // Sowing, Growing, Harvesting, OffSeason
        public string BanglaCropStage { get; set; } = "বাড়ন্ত পর্যায়";
        
        public int CurrentMonth { get; set; } = DateTime.Today.Month;
        public string CurrentMonthName { get; set; } = DateTime.Today.ToString("MMMM");

        public RegionalWeatherForecast Weather { get; set; } = new();

        public bool RainAlert { get; set; } = false;
        public double MaxRainChance { get; set; } = 0.0;
        public int RainWindowDays { get; set; } = 0; // within next N days

        public string OverallRiskLevel { get; set; } = "Advisory"; // Urgent, High, Moderate, Optimal
        public string OverallBadgeClass { get; set; } = "warning";
        public string BannerTitle { get; set; } = string.Empty;
        public string BanglaBannerTitle { get; set; } = string.Empty;
        public string BannerMessage { get; set; } = string.Empty;
        public string BanglaBannerMessage { get; set; } = string.Empty;

        public bool HasProfileCrop { get; set; } = true;
        public bool HasProfileDistrict { get; set; } = true;

        public List<WeatherSuggestionItem> Suggestions { get; set; } = new();
    }

    /// <summary>
    /// Interactive Advisory model for browsing/simulating weather suggestions across districts & crops.
    /// </summary>
    public class WeatherSuggestionAdvisoryViewModel
    {
        public string SelectedDistrict { get; set; } = "Bogra";
        public string SelectedCrop { get; set; } = "Rice (Boro)";
        public IReadOnlyList<string> AvailableDistricts { get; set; } = OnboardingOptions.Districts;
        public IReadOnlyList<string> AvailableCrops { get; set; } = OnboardingOptions.Crops;
        public WeatherSuggestionViewModel Suggestion { get; set; } = new();
        public List<WeatherSuggestionItem> AllGeneratedItems { get; set; } = new();
    }
}
